export const GET_ALLVIDEOGAMES = "GET_ALLVIDEOGAMES";
export const GET_DETAILGAME = "GET_DETAILGAME";
export const CLEAR_DETAILGAME = "CLEAR_DETAILGAME";
export const GET_GENRES = "GET_GENRES";
export const GET_PLATAFOMS = 'GET_PLATAFOMS'
export const GET_GAME_BYNAME = "GET_GAME_BYNAME";
export const FILTER_LISTGENRES = "FILTER_LISTGENRES";
export const GET_CREATED = "GET_CREATED"
export const ORDER_LIST = "ORDER_LIST"
export const RATING_ORDER = "RATING_ORDER"
export const PAGINATE = "PAGINATE";
export const FILTER_LISTPLATFORMS = "FILTER_LISTPLATFORMS";

export const ADD_NEW_GAME = 'ADD_NEW_GAME'